- name: Base facts
  ansible.builtin.set_fact:
    dop_bin: "{{ (user_home_path, 'bin') | path_join }}"
    dop_temp: "{{ (dop_home_path, 'tmp') | path_join }}"

- name: Temp
  ansible.builtin.file:
     path: "{{ dop_temp }}"
     state: directory

- name: Base for Windows
  ansible.builtin.include_tasks:
    file: base_windows.yml
  when: "'Windows' in ansible_system"

- name: Base for Windows
  ansible.builtin.include_tasks:
    file: base_linux.yml
  when: "'Linux' in ansible_system"

- name: Base for MacOS
  ansible.builtin.include_tasks:
    file: base_macos.yml
  when: "'Darwin' in ansible_system"
