- name: Base facts
  ansible.builtin.set_fact:
    dop_bin: "{{ (user_home_path, 'bin') | path_join }}"
    dop_temp: "{{ (dop_home_path, 'tmp') | path_join }}"

- name: Base for Windows
  ansible.builtin.include_tasks:
    file: base_windows.yml
  when: "'Windows' in ansible_system"
