user.email:
  title: User's E-Mail address
  default: ''
  type: string

user.name:
  title: User's Name
  description: For example - `John Doe`
  default: ''
  type: string

# Codex options
codex.plugins.source:
  title: DevOps Pass AI plugins source
  description: |
    DOP AI Plugins Git repo URL.
    !!! **After changing of that setting you have to restart DevOps Pass AI.**
  type: string
  default: 'https://github.com/devopspass/plugins.git'
  section: DevOps Pass AI

codex.index.do_indexing:
  default: 1

codex.index:
  default: {}
