user.email:
  title: User's E-Mail address
  default: ''
  type: string

user.name:
  title: User's Name
  description: For example - `John Doe`
  default: ''
  type: string

terminal.command:
  title: Terminal command
  type: string
  description: Terminal command
  default_windows: cmd /C %COMMAND%
  default_linux: gnome-terminal -- %COMMAND%
  section: DevOps Pass AI

# Codex options
codex.plugins.source:
  title: DevOps Pass AI plugins source
  description: |
    Plugins Git repo URL.
    !!! **After changing of that setting you have to restart DevOps Pass AI.**
  type: string
  default: 'https://github.com/devopspass/plugins.git'
  section: DevOps Pass AI

codex.plugins.source_branch:
  title: DevOps Pass AI plugins branch
  description: |
    Plugins Git repo branch
    !!! **After changing of that setting you have to restart DevOps Pass AI.**
  type: string
  default: main
  section: DevOps Pass AI

codex.plugins.source_hard_reset:
  title: Reset Plugins local changes
  description: |
    !!! **After changing of that setting you have to restart DevOps Pass AI.**
  type: checkbox
  default: main
  section: DevOps Pass AI

codex.index.do_indexing:
  default: 1

codex.index:
  default: {}
