---
- name: Install Git
  hosts: localhost
  connection: local
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64
  tasks:
    - name: Base tasks
      ansible.builtin.include_tasks:
        file: "../../_common/playbooks/base.yml"

#####################################################################
#
#           Windows
#
#####################################################################
    - name: Install Git on Windows
      block:
        - name: Fetch latest Git version from website
          ansible.builtin.uri:
            url: https://git-scm.com/download/win
            return_content: true
          register: git_url_page

        - name: Set fact with the latest WinSCP version
          ansible.builtin.set_fact:
            git_url: "{{ git_url_page.content | regex_search('https://github.com/git-for-windows/git/releases/download/v.*.windows.1/Git-.*-64-bit.exe') }}"
          
        - name: Download Putty binary
          ansible.builtin.get_url:
            url: "{{ git_url }}"
            dest: "{{ dop_temp }}\\\\git-setup.exe"

        - name: Run git installation
          ansible.builtin.command:
            cmd: "{{ dop_temp | regex_escape }}\\\\git-setup.exe /silent"
            chdir: "{{ dop_temp }}"

        - name: Remove binary
          ansible.builtin.file:
            path: "{{ dop_temp | regex_escape }}\\\\git-setup.exe"
            state: absent
