---
- name: Configure Git global user name and email
  hosts: localhost  # You can change this to the appropriate host or group

  tasks:
    - name: Set Git user name
      ansible.builtin.git_config:
        scope: global
        name: user.name
        value: "{{ user_name }}"

    - name: Set Git user email
      ansible.builtin.git_config:
        scope: global
        name: user.email
        value: "{{ user_email }}"
