---
- name: Configure Git global user name and email
  hosts: localhost
  connection: local

  tasks:
    - name: Set git config for MacOS/*nix
      ansible.builtin.set_fact:
        git_config_path: "{{ ansible_env.HOME }}/.gitconfig"
      when: "'Darwin' in ansible_system or 'Linux' in ansible_system"

    - name: Set git config for Windows
      ansible.builtin.set_fact:
        git_config_path: "{{ ansible_env.USERPROFILE }}\\.gitconfig"
      when: "'Windows' in ansible_os_family"

    - name: Git configure User name and E-Mail
      ansible.builtin.ini_file:
        path: "{{ git_config_path }}"
        section: user
        option: "{{ item.key }}"
        value: "{{ item.value }}"
      with_items:
        - { key: 'name', value: "{{ user_name }}" }
        - { key: 'email', value: "{{ user_email }}" }
