k9s_install:
  object_types: application
  application_name: Kubernetes
  title: Install K9s
  description: |
    Install `k9s` on your local.
    K9s provides a terminal UI to interact with your Kubernetes clusters.
    Versions list can be found here - https://github.com/derailed/k9s, **latest** version will install latest stable version of `k9s`
  icon: fas fa-download
  playbook: plugins/kubernetes/playbooks/install_k9s.yml
  required_options:
    req_k9s_version:
      title: K9s version to install
      remember: true
      remember_key: name
      type: string
      default: latest

kubectl_install:
  object_types: application
  application_name: Kubernetes
  title: Install kubectl
  description: |
    Install `kubectl` on your local. Versions list can be found here - https://github.com/kubernetes/kubernetes/releases/, **latest** version will install latest stable version of `kubectl`
  icon: fas fa-download
  playbook: plugins/kubernetes/playbooks/install_kubectl.yml
  required_options:
    req_kubectl_version:
      title: kubectl version to install
      remember: true
      remember_key: name
      type: string
      default: latest

k8s_add_context:
  object_types: application
  application_name: Kubernetes
  title: Add KubeConfig
  description: |
    Add KubeConfig to ~/.kube/config, if context/server/user exists it will be overriden
  icon: fas fa-folder-plus
  command: plugins/kubernetes/actions/k8s_add_context.py
  required_options:
    kube_config:
      title: KubeConfig
      remember: false

k8s_set_default_context:
  title: Set context as default
  icon: fas fa-star
  object_types: k8s_context
  command: |
    plugins/kubernetes/actions/set_default_context.py

k8s_open_web_console:
  title: Open web-console
  icon: fab fa-chrome
  object_types: k8s_context
  command: |
    plugins/kubernetes/actions/oc_open_console.py

k8s_open_context:
  title: Open in K9s
  icon: fas fa-terminal
  object_types: k8s_context
  required_settings:
    - terminal.command
  command: |
    plugins/kubernetes/actions/open_in_k9s.py

k8s_set_default_ns:
  title: Set Namespace as default
  icon: fas fa-star
  object_types: k8s_namespace
  command: |
    plugins/kubernetes/actions/set_default_ns.py

k8s_open_namespace:
  title: Open in K9s
  icon: fas fa-terminal
  object_types: k8s_namespace
  required_settings:
    - terminal.command
  command: |
    plugins/kubernetes/actions/open_in_k9s.py
