---
- name: Install helm
  hosts: localhost
  connection: local
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64
  tasks:
    - name: Base tasks
      ansible.builtin.include_tasks:
        file: "../../_common/playbooks/base.yml"

    - name: Fetch latest Helm version from Kubernetes GitHub releases
      ansible.builtin.uri:
        url: "https://api.github.com/repos/helm/helm/releases/latest"
        return_content: true
        headers:
          Accept: "application/vnd.github.v3+json"
      register: helm_version_response

    - name: Parse latest Helm version
      ansible.builtin.set_fact:
        latest_helm_version: "{{ helm_version_response.json.tag_name | regex_replace('^v', '') }}"

    - name: Set version
      ansible.builtin.set_fact:
        helm_version: "{{ (req_helm_version == 'latest') | ternary(latest_helm_version, req_helm_version)}}"

#####################################################################
#
#           Linux/MacOS
#
#####################################################################
    - name: Install helm on macOS/Linux
      block:
        - name: Set facts based on operating system
          ansible.builtin.set_fact:
            helm_download_url: "https://get.helm.sh/helm-v{{ helm_version }}-{{ ansible_system | lower }}-{{ arch_mapping[ansible_architecture] }}.tar.gz"

        - name: Download Helm binary
          ansible.builtin.get_url:
            url: "{{ helm_download_url }}"
            dest: "{{ dop_temp }}/helm.tar.gz"

        - name: Unzip Helm binary
          dop_unarchive:
            src: "{{ dop_temp }}/helm.tar.gz"
            dest: "{{ dop_temp }}/"

        - name: Move Helm binary
          ansible.builtin.command:
            cmd: "mv {{ helm_path }} {{ ansible_env.HOME }}/bin/"
            removes: "{{ helm_path }}"
          vars:
            helm_path: "{{ dop_temp }}/{{ ansible_system | lower }}-{{ arch_mapping[ansible_architecture] }}/helm"

        - name: Remove Helm temporary folder
          ansible.builtin.file:
            path: "{{ helm_path }}"
            state: absent
          vars:
            helm_path: "{{ ansible_env.HOME }}/bin/{{ ansible_system | lower }}-{{ arch_mapping[ansible_architecture] }}/"
            
      when: "'Darwin' in ansible_system or 'Linux' in ansible_system"

#####################################################################
#
#           Windows
#
#####################################################################
    - name: Install helm on Windows
      when: "'Windows' in ansible_system"
      block:
        - name: Set facts based on operating system
          ansible.builtin.set_fact:
            helm_download_url: "https://get.helm.sh/helm-v{{ helm_version }}-{{ ansible_system | lower }}-{{ arch_mapping[ansible_architecture] }}.zip"

        - name: Download Helm binary
          ansible.builtin.get_url:
            url: "{{ helm_download_url }}"
            dest: "{{ dop_temp }}\\\\helm.zip"

        - name: Extract Helm binary # noqa: command-instead-of-module no-changed-when
          ansible.builtin.command:
            cmd: "tar -xf helm.zip"
            chdir: "{{ dop_temp }}"

        - name: Move Helm binary
          ansible.builtin.command:
            cmd: "move {{ helm_path }} {{ dop_bin | regex_escape }}"
          vars:
            helm_path: "{{ dop_temp | regex_escape }}\\\\{{ ansible_system | lower }}-{{ arch_mapping[ansible_architecture] }}\\\\helm.exe"

    - name: Helm version
      ansible.builtin.debug:
        msg: "Installed Helm version is {{ helm_version }}"
