---
- name: DevOps Pass AI
  hosts: localhost
  connection: local
  tasks:
    - name: Base tasks
      ansible.builtin.include_tasks:
        file: "../../_common/playbooks/base.yml"
    
    - name: Split text
      ansible.builtin.set_fact:
        sec: "{{ app_sections.split('\n') }}"

    - name: Get sections names
      set_fact:
        sec1: "{{ (sec1 | default([])) + [{'name': item, 'urls': [{'name': 'name', 'url': 'https://devopspass-ai.com/'}]}] }}"
      with_items: "{{ sec }}"

    - name: App section
      yedit:
        src: "{{ ( plugins_path, 'apps.yaml' ) | path_join }}"
        append: true
        value: |
          name: "{{ app_name }}"
          icon: "{{ app_icon_url }}"
          description: "{{ app_description }}"
          description_long: |
            {{ app_description_long }}
          sections: {{ sec1 }}

    - name: Folder name
      ansible.builtin.set_fact:
        fname: "{{ app_name | lower | replace(' ', '_') }}"

    - name: Folder path
      ansible.builtin.set_fact:
        fpath: "{{ (plugins_path, fname) | path_join }}"

    - name: App folder
      ansible.builtin.file:
        path: "{{ fpath }}"
        state: directory

    - name: Install action file
      ansible.builtin.template:
        dest: "{{ (fpath, 'actions.yaml') | path_join }}"
        src: 'actions.yaml.j2'
      vars:
        action_name: "install"

    - name: Playbook folder
      ansible.builtin.file:
        path: "{{ ( fpath, 'playbooks' ) | path_join }}"
        state: directory

    - name: Install action playbook
      ansible.builtin.template:
        dest: "{{ (fpath, 'playbooks', 'install.yml') | path_join }}"
        src: 'install_playbook.yml.j2'
