helm_install:
  object_types: application
  application_name: Helm
  title: Install Helm
  description: |
    Install **Helm** on your local. Versions list can be found here - https://github.com/helm/helm/releases, **latest** version will install latest stable version of `Helm`
  icon: fas fa-download
  playbook: plugins/helm/playbooks/install_helm.yml
  required_options:
    req_helm_version:
      title: Helm3 version to install
      remember: true
      remember_key: name
      type: string
      default: latest

helm_add_repo:
  object_types: application
  application_name: Helm
  title: Add Helm repo
  description: |
    Add Helm repo source
  icon: fas fa-folder-plus
  command: plugins/helm/scripts/helm_add_repo.py
  required_options:
    repo_name:
      title: Short repo name
      remember: true
      remember_key: name
      type: string
    repo_url:
      title: Repo URL
      remember: true
      remember_key: name
      type: string

helm_refresh_repo:
  title: Refresh info
  icon: fas fa-sync-alt
  object_types: helm_repo
  command: plugins/helm/scripts/helm_refresh_repo.py
  show_terminal: true
  remember: true
  remember_key: name

helm_delete_repo:
  title: Remove repo
  icon: fas fa-trash
  object_types: helm_repo
  command: plugins/helm/scripts/helm_remove_repo.py
  danger: true

helm_chart_install:
  title: Install Chart
  icon: fas fa-download
  description: Install Helm chart in current Kubernetes context (cluster/namespace)
  object_types: helm_repo_chart
  command: plugins/helm/scripts/helm_install_chart.py
  required_options:
    chart_name:
      title: Installed Helm chart name
      description: How you want to call installed Chart
      remember: true
      remember_key: name
      type: string
    chart_values:
      title: Helm chart values
      description: Specify one per line, like `service.nodePorts.http=8080`
      remember: true
      remember_key: name
      type: text

helm_open_chart_sources:
  title: Open Chart Source
  icon: fas fa-file-code
  object_types: helm_repo_chart
  command: plugins/helm/scripts/helm_open_chart_sources.py

helm_test_release:
  title: Test Release
  icon: fas fa-vial
  object_types: helm_release
  command: plugins/helm/scripts/helm_test_release.py

helm_delete_release:
  title: Remove Release
  icon: fas fa-trash
  object_types: helm_release
  command: plugins/helm/scripts/helm_remove_release.py
  danger: true
