---
- name: Generate Docker Compose
  hosts: localhost
  connection: local
  tasks:
    - name: Generate docker-compose.yml
      ansible.builtin.template:
        src: "templates/_compose.yml.j2"
        dest: "{{ (folder_name, 'compose.yml') | path_join }}"

    - name: Generate nginx.conf
      when: "'true' in nginx_enabled"
      ansible.builtin.template:
        src: "templates/_compose.nginx.conf.j2"
        dest: "{{ (folder_name, 'nginx.conf') | path_join }}"
