---
- name: Install Putty/Kitty/WinSCP
  hosts: localhost
  connection: local
  vars:
    arch_mapping:  # Map ansible architecture {{ ansible_architecture }} names to Docker's architecture names
      x86_64: amd64
      aarch64: arm64
  tasks:
    - name: Base tasks
      ansible.builtin.include_tasks:
        file: "../../_common/playbooks/base.yml"

#####################################################################
#
#           Windows
#
#####################################################################
    - name: Install Putty on Windows
      when: "'Windows' in ansible_system"
      block:
        - name: Set facts based on operating system
          ansible.builtin.set_fact:
            download_url: "https://www.9bis.net/kitty/files/kitty_portable.exe"
            fname: kitty
          when: ssh_tool == "Kitty"

        - name: Set facts based on operating system
          ansible.builtin.set_fact:
            download_url: "https://the.earth.li/~sgtatham/putty/latest/w64/putty.exe"
            fname: putty
          when: ssh_tool == "Putty"

        - name: Download Putty binary
          ansible.builtin.get_url:
            url: "{{ download_url }}"
            dest: "{{ dop_bin }}\\\\{{ fname }}.exe"

    - name: Install WinSCP on Windows
      when: "'Windows' in ansible_system"
      block:
        - name: Fetch latest WinSCP version from website
          ansible.builtin.uri:
            url: https://winscp.net/eng/downloads.php
            return_content: true
          register: winscp_version_page

        - name: Set fact with the latest WinSCP version
          ansible.builtin.set_fact:
            winscp_version: "{{ winscp_version_page.content | regex_search('WinSCP-[0-9]+.[0-9]+.[0-9]+-Portable.zip') }}"

        - name: Download WinSCP binary
          ansible.builtin.get_url:
            url: "https://winscp.net/download/{{ winscp_version }}"
            dest: "{{ dop_temp }}\\\\WinSCP.zip"

        - name: Extract binary
          ansible.builtin.command:
            cmd: "tar -xf WinSCP.zip -C '{{ dop_bin }}'"
            chdir: "{{ dop_temp }}"

    - name: version
      ansible.builtin.debug:
        msg: "WinSCP - {{ winscp_version }}"

    - name: version
      ansible.builtin.debug:
        msg: "Putty/Kitty - {{ fname }}"
